
name: Build GUI Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./gui

      - name: Build Windows application
        run: flutter build windows --release
        working-directory: ./gui

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reboot-launcher-windows
          path: |
            gui/build/windows/x64/runner/Release/
            gui/build/windows/x64/runner/Release/*.exe
            gui/build/windows/x64/runner/Release/*.dll
